/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./*.html', './templates/**/*.html', './static/js/**/*.js'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#ecf0fe',
        'surface-container-high': '#e4e8f6',
        'secondary-fixed': '#d7e2ff',
        'primary-container': '#003f87',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#001a40',
        'on-surface': '#171c25',
        'on-secondary-fixed': '#001a40',
        'on-tertiary': '#ffffff',
        primary: '#002a5d',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#ffb597',
        'inverse-surface': '#2b303b',
        'secondary-fixed-dim': '#acc7ff',
        'primary-fixed': '#d7e2ff',
        'inverse-primary': '#acc7ff',
        'on-tertiary-fixed-variant': '#7a2f07',
        'tertiary-container': '#732a02',
        'tertiary-fixed': '#ffdbcd',
        tertiary: '#501a00',
        'on-surface-variant': '#434751',
        'on-secondary-fixed-variant': '#004491',
        'on-error-container': '#93000a',
        'on-secondary-container': '#003370',
        'surface-bright': '#f9f9ff',
        background: '#f9f9ff',
        'surface-variant': '#dee2f0',
        'primary-fixed-dim': '#acc7ff',
        'on-primary-fixed-variant': '#0d458d',
        secondary: '#115cb9',
        'on-tertiary-container': '#fb9263',
        error: '#ba1a1a',
        'surface-container-low': '#f0f3ff',
        'on-primary': '#ffffff',
        'outline-variant': '#c3c6d2',
        'surface-tint': '#305da6',
        'surface-container': '#e9eefc',
        'on-background': '#171c25',
        'surface-container-highest': '#dee2f0',
        'surface-container-lowest': '#ffffff',
        surface: '#f9f9ff',
        'on-primary-container': '#84adfc',
        outline: '#737782',
        'on-tertiary-fixed': '#360f00',
        'on-error': '#ffffff',
        'surface-dim': '#d5dae7',
        'secondary-container': '#659dfe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'margin-mobile': '16px',
        'container-max-width': '1440px',
        gutter: '24px',
        'stack-lg': '32px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'label-lg': ['Inter'],
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'label-sm': ['Inter'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
